apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kubevirt-operators
  namespace: openshift-operator-lifecycle-manager
spec:
  sourceType: grpc
  image: docker.io/lveyde/kubevirt-operators:0.3
  displayName: KubeVirt Operators
  publisher: Red Hat
